import type { OnecoreState } from "./types";

export const DEFAULT_REFUND_POLICY_ID = "refund-standard";

export function seedOnecoreState(): OnecoreState {
  return {
    artists: [
      {
        id: "artist-kimogi",
        name: "김오기",
        genre: "재즈",
        tagline: "홍대 밤을 재즈로 채우는 보컬",
        bio: "팬들이 먼저 불러낸 단독 밤. 작은 클럽에서 큰 호흡으로 부릅니다.",
      },
      {
        id: "artist-moon",
        name: "문미향",
        genre: "재즈",
        tagline: "피아노와 목소리의 듀오 감성",
        bio: "감성 재즈 세트로 홍대 팬들과 맞춰 온 아티스트입니다.",
      },
    ],
    venueCandidates: [
      { id: "venue-ff", name: "홍대 클럽 FF", district: "홍대", capacity: 180, note: "1순위 후보" },
      { id: "venue-velvet", name: "벨벳 라운지", district: "홍대", capacity: 120 },
      { id: "venue-modeci", name: "모데시 홀", district: "마포", capacity: 220 },
    ],
    users: [
      { id: "user-mike", handle: "mike_seoul", displayName: "Mike" },
      { id: "user-yuna", handle: "yuna_jazz", displayName: "유나" },
      { id: "user-han", handle: "han_core", displayName: "한코어" },
    ],
    refundPolicies: [
      {
        id: DEFAULT_REFUND_POLICY_ID,
        title: "표준 환불",
        summary: "공연 준비가 진행되지 않으면 예치금 전액 환불",
        rules: [
          "목표 미달 시 마감 후 자동 환불",
          "아티스트·공연장·일정 확정 실패 시 자동 환불",
          "공연 준비 단계 진입 후에도 일정 확정 실패 시 환불",
          "환불은 결제 수단으로 3–5영업일 내 처리",
        ],
      },
    ],
    races: [
      {
        id: "race-kimogi-jazz-ff",
        title: "김오기 · 홍대 재즈 단독 밤",
        artistId: "artist-kimogi",
        proposalReason:
          "홍대에서 재즈 라이브를 자주 해왔지만, 팬 100명의 core가 모이기 전까지는 단독 공연으로 이어지지 않습니다. 이번 라운드는 ‘팬이 먼저 불러낸 밤’을 증명하는 제안입니다.",
        targetCount: 100,
        currentCount: 34,
        deadline: "2026-06-15",
        deadlineCountdown: { days: 6, hours: 2, minutes: 18 },
        status: "active",
        paymentType: "deposit",
        depositAmount: 30000,
        refundPolicyId: DEFAULT_REFUND_POLICY_ID,
        preferredDate: "2026-07-12 (토)",
        backupDates: ["2026-07-19 (토)", "2026-07-26 (토)"],
        venueCandidateIds: ["venue-ff", "venue-velvet"],
        artistConfirmationStatus: "pending",
        venueConfirmationStatus: "pending",
        showPreparationStatus: "not_started",
      },
      {
        id: "race-moon-prep-demo",
        title: "문미향 · 공연 준비 단계 데모",
        artistId: "artist-moon",
        proposalReason: "목표 달성 이후 공연 준비 파이프라인을 보여주는 샘플 라운드입니다.",
        targetCount: 100,
        currentCount: 100,
        deadline: "2026-05-20",
        deadlineCountdown: { days: 0, hours: 0, minutes: 0 },
        status: "artist_contacting",
        paymentType: "deposit",
        depositAmount: 30000,
        refundPolicyId: DEFAULT_REFUND_POLICY_ID,
        preferredDate: "2026-08-02 (토)",
        backupDates: ["2026-08-09 (토)"],
        venueCandidateIds: ["venue-modeci"],
        artistConfirmationStatus: "confirmed",
        venueConfirmationStatus: "pending",
        showPreparationStatus: "in_progress",
        artistContactChannel: "instagram_dm",
        artistContactTarget: "@moonmihyang.official",
        artistOutreachNote: "100코어 달성 안내와 private invitation 발송 준비",
        artistResponseDeadline: "2026-05-27",
        assignedVenueId: "venue-ff",
        venueHoldUntil: "2026-05-30",
        productionCostEstimate: 1200000,
        scoutFeePercent: 3,
        platformFeePercent: 8,
        minTicketPrice: 35000,
        termsNote: "아티스트 payout 우선. 베뉴는 고정 대관료 기준으로 협상.",
        refundReviewDate: "2026-06-18",
      },
    ],
    commitments: [
      {
        id: "core-1",
        raceId: "race-kimogi-jazz-ff",
        userId: "user-yuna",
        amount: 30000,
        createdAt: "2026-05-20T10:00:00.000Z",
        displayConsent: true,
        displayName: "유나",
        isAnonymous: false,
      },
      {
        id: "core-2",
        raceId: "race-kimogi-jazz-ff",
        userId: "user-han",
        amount: 30000,
        createdAt: "2026-05-21T14:00:00.000Z",
        displayConsent: true,
        isAnonymous: true,
      },
    ],
    paymentIntents: [],
    eventLogs: [
      {
        id: "log-seed-1",
        raceId: "race-kimogi-jazz-ff",
        changedBy: "admin@fanstage",
        fromStatus: "draft",
        toStatus: "active",
        reason: "MVP 시드 · 라운드 오픈",
        timestamp: "2026-05-18T09:00:00.000Z",
        visibleToPublic: true,
      },
      {
        id: "log-seed-2",
        raceId: "race-moon-prep-demo",
        changedBy: "system",
        fromStatus: "active",
        toStatus: "target_reached",
        reason: "목표 core 인원 달성",
        timestamp: "2026-05-19T11:00:00.000Z",
        visibleToPublic: true,
      },
      {
        id: "log-seed-3",
        raceId: "race-moon-prep-demo",
        changedBy: "system",
        fromStatus: "target_reached",
        toStatus: "show_preparation",
        reason: "공연 준비 단계로 전환",
        timestamp: "2026-05-19T11:00:01.000Z",
        visibleToPublic: true,
      },
      {
        id: "log-seed-4",
        raceId: "race-moon-prep-demo",
        changedBy: "admin@fanstage",
        fromStatus: "show_preparation",
        toStatus: "artist_contacting",
        reason: "아티스트 측 private invitation 준비",
        timestamp: "2026-05-20T09:30:00.000Z",
        visibleToPublic: true,
      },
    ],
  };
}
