import type { OnecoreState } from "./types";

export const DEFAULT_REFUND_POLICY_ID = "refund-standard";

export function seedOnecoreState(): OnecoreState {
  return {
    artists: [
      {
        id: "artist-kimogi",
        name: "김오기",
        genre: "재즈",
        tagline: "홍대 밤을 재즈로 채우는 보컬",
        bio: "팬들이 먼저 불러낸 단독 밤. 작은 클럽에서 큰 호흡으로 부릅니다.",
        battlePitch: "즉흥 리드와 공간 장악. FF 신인 나이트에서 가장 빠르게 올라온 모던 재즈.",
        social: { primaryPlatform: "instagram", instagram: "kimoki_jazz", youtube: "kimokijazz", spotify: "kimoki" },
      },
      {
        id: "artist-moon",
        name: "문미향",
        genre: "재즈",
        tagline: "피아노와 목소리의 듀오 감성",
        bio: "감성 재즈 세트로 홍대 팬들과 맞춰 온 아티스트입니다.",
        battlePitch: "심야 연기와 브라스 열기. FF 재즈 보컬의 중심.",
        social: { primaryPlatform: "tiktok", tiktok: "moonmihyang", instagram: "moon_vocal" },
      },
    ],
    venueCandidates: [
      {
        id: "venue-ff",
        name: "홍대 클럽 FF",
        district: "홍대",
        capacity: 180,
        note: "1순위 후보",
        estimatedTicketMin: 35000,
        estimatedTicketMax: 55000,
      },
      {
        id: "venue-velvet",
        name: "벨벳 라운지",
        district: "홍대",
        capacity: 120,
        estimatedTicketMin: 40000,
        estimatedTicketMax: 60000,
      },
      {
        id: "venue-modeci",
        name: "모데시 홀",
        district: "마포",
        capacity: 220,
        estimatedTicketMin: 45000,
        estimatedTicketMax: 70000,
      },
    ],
    scoutCampaigns: [
      {
        id: "scout-kimogi-hd",
        scoutId: "user-mike",
        artistId: "artist-kimogi",
        targetCity: "서울 · 홍대",
        whyNow: "재즈 라이브 수요가 다시 올라오는 시즌. 김오기는 홍대에서 이미 입소문이 있음.",
        estimatedDemand: "core 80–120명 가능",
        venueSuggestions: "클럽 FF, 벨벳 — 소형 재즈룸",
        rallyCopy: "홍대에서 김오기 단독 밤을 팬이 먼저 불러옵니다. 100 core가 모이면 fanstage가 비공개로 이어갑니다.",
        scoutConfidence: "high",
        handoffState: "rally_live",
        raceId: "race-kimogi-jazz-ff",
        createdAt: "2026-05-18T08:00:00.000Z",
      },
    ],
    users: [
      { id: "user-mike", handle: "mike_seoul", displayName: "Mike" },
      { id: "user-yuna", handle: "yuna_jazz", displayName: "유나" },
      { id: "user-han", handle: "han_core", displayName: "한코어" },
    ],
    refundPolicies: [
      {
        id: DEFAULT_REFUND_POLICY_ID,
        title: "표준 환불",
        summary: "공연이 열리지 않으면 예치금 전액 환불",
        rules: [
          "목표 미달 시 마감 후 자동 환불",
          "아티스트·공연장·일정 확정 실패 시 자동 환불",
          "환불은 결제 수단으로 3–5영업일 내 처리",
        ],
      },
    ],
    races: [
      {
        id: "race-kimogi-jazz-ff",
        title: "김오기 · 홍대 재즈 단독 밤",
        artistId: "artist-kimogi",
        targetCity: "서울 · 홍대",
        adminPhase: "collecting_demand",
        proposalReason:
          "홍대에서 재즈 라이브 수요를 팬이 먼저 증명합니다. 100 core가 모이면 fanstage가 비공개로 아티스트·공연장을 연결합니다.",
        targetCount: 100,
        currentCount: 34,
        deadline: "2026-06-15",
        deadlineCountdown: { days: 6, hours: 2, minutes: 18 },
        status: "active",
        paymentType: "deposit",
        depositAmount: 30000,
        refundPolicyId: DEFAULT_REFUND_POLICY_ID,
        preferredDate: "2026-07-12 (토)",
        backupDates: ["2026-07-19 (토)", "2026-07-26 (토)"],
        venueCandidateIds: ["venue-ff", "venue-velvet", "venue-modeci"],
        fanNoteSamples: ["홍대 재즈 단독 기다렸어요", "FF에서 보고 싶어요"],
        artistConfirmationStatus: "pending",
        venueConfirmationStatus: "pending",
        showPreparationStatus: "not_started",
      },
      {
        id: "race-moon-prep-demo",
        title: "문미향 · 공연 준비 단계 데모",
        artistId: "artist-moon",
        targetCity: "서울 · 홍대",
        adminPhase: "artist_reviewing_invite",
        proposalReason: "100 core 달성 후 비공개 아티스트 초대·공연장 매칭 데모.",
        targetCount: 100,
        currentCount: 100,
        deadline: "2026-05-20",
        deadlineCountdown: { days: 0, hours: 0, minutes: 0 },
        status: "artist_reviewing_invite",
        paymentType: "deposit",
        depositAmount: 30000,
        refundPolicyId: DEFAULT_REFUND_POLICY_ID,
        preferredDate: "2026-08-02 (토)",
        backupDates: ["2026-08-09 (토)"],
        venueCandidateIds: ["venue-ff", "venue-velvet"],
        shortlistedVenueIds: ["venue-ff", "venue-velvet"],
        fanNoteSamples: ["문미향 피아노 세트 꼭 보고 싶어요"],
        artistInviteToken: "inv-moon-demo",
        artistInviteSentAt: "2026-05-20T10:00:00.000Z",
        artistConfirmationStatus: "pending",
        venueConfirmationStatus: "pending",
        showPreparationStatus: "in_progress",
        artistContactChannel: "instagram_dm",
        artistContactTarget: "@moonmihyang.official",
        artistOutreachNote: "100 core 달성 · private invite 발송됨",
        artistResponseDeadline: "2026-05-27",
        productionCostEstimate: 1200000,
        scoutFeePercent: 3,
        platformFeePercent: 8,
        minTicketPrice: 35000,
        termsNote: "아티스트 payout 우선",
        refundReviewDate: "2026-06-18",
      },
      {
        id: "race-moon-ticket-open-demo",
        title: "문미향 · 홍대 FF 단독 밤",
        artistId: "artist-moon",
        targetCity: "서울 · 홍대",
        adminPhase: "ticketing_ready",
        proposalReason: "100코어 수요 증명 이후 아티스트 수락 및 베뉴 확정 단계 데모.",
        targetCount: 100,
        currentCount: 100,
        deadline: "2026-05-22",
        deadlineCountdown: { days: 0, hours: 0, minutes: 0 },
        status: "ticketing_ready",
        paymentType: "deposit",
        depositAmount: 30000,
        refundPolicyId: DEFAULT_REFUND_POLICY_ID,
        preferredDate: "2026-08-16 (토)",
        backupDates: ["2026-08-23 (토)"],
        venueCandidateIds: ["venue-ff", "venue-velvet"],
        shortlistedVenueIds: ["venue-ff"],
        assignedVenueId: "venue-ff",
        fanNoteSamples: ["문미향 FF 단독 밤 기다렸어요"],
        artistInviteToken: "inv-moon-ticket-open",
        artistInviteSentAt: "2026-05-21T10:00:00.000Z",
        artistConfirmationStatus: "confirmed",
        venueConfirmationStatus: "confirmed",
        showPreparationStatus: "in_progress",
        artistContactChannel: "instagram_dm",
        artistContactTarget: "@moonmihyang.official",
        artistOutreachNote: "아티스트 수락 완료 · 베뉴 확정",
        artistResponseDeadline: "2026-05-24",
        productionCostEstimate: 1300000,
        scoutFeePercent: 3,
        platformFeePercent: 8,
        minTicketPrice: 30000,
        termsNote: "추가 티켓 오픈 단계",
        refundReviewDate: "2026-06-22",
      },
    ],
    commitments: [
      {
        id: "core-1",
        raceId: "race-kimogi-jazz-ff",
        userId: "user-yuna",
        amount: 30000,
        createdAt: "2026-05-20T10:00:00.000Z",
        displayConsent: true,
        displayName: "유나",
        isAnonymous: false,
      },
      {
        id: "core-2",
        raceId: "race-kimogi-jazz-ff",
        userId: "user-han",
        amount: 30000,
        createdAt: "2026-05-21T14:00:00.000Z",
        displayConsent: true,
        isAnonymous: true,
      },
    ],
    paymentIntents: [],
    eventLogs: [
      {
        id: "log-seed-1",
        raceId: "race-kimogi-jazz-ff",
        changedBy: "admin@fanstage",
        fromStatus: "draft",
        toStatus: "active",
        reason: "수요 캠페인 오픈",
        timestamp: "2026-05-18T09:00:00.000Z",
        visibleToPublic: true,
      },
      {
        id: "log-seed-2",
        raceId: "race-moon-prep-demo",
        changedBy: "system",
        fromStatus: "active",
        toStatus: "target_reached",
        reason: "100 core · 수요 증명",
        timestamp: "2026-05-19T11:00:00.000Z",
        visibleToPublic: true,
      },
      {
        id: "log-seed-3",
        raceId: "race-moon-prep-demo",
        changedBy: "system",
        fromStatus: "target_reached",
        toStatus: "artist_contacting",
        reason: "비공개 아티스트 연락 시작",
        timestamp: "2026-05-19T11:00:01.000Z",
        visibleToPublic: true,
      },
      {
        id: "log-seed-4",
        raceId: "race-moon-prep-demo",
        changedBy: "admin@fanstage",
        fromStatus: "artist_contacting",
        toStatus: "artist_reviewing_invite",
        reason: "비공개 초대장 발송",
        timestamp: "2026-05-20T09:30:00.000Z",
        visibleToPublic: true,
      },
    ],
  };
}
